### PR TITLE
Adapt to use Yojson 2.0 API (retry #299)

### PR DESCRIPTION
**Pull request by mjambon**
This branch should be equivalent to the original https://github.com/ahrefs/atd/pull/299 by @Leonidas-from-XIV which got merged and then unmerged from `master`.

We're now waiting for a test to pass, which depends on a fix in yojson. Once yojson 2.0.2 is available, this should be good to merge. We have to run `make test` manually if the CI pipeline is broken due to problems with opam package versions.

### PR checklist

- [x] New code has tests to catch future regressions
- [x] Documentation is up-to-date
- [x] `CHANGES.md` is up-to-date

### CODE REVIEW

**Comment by mjambon** [comment]
I confirm that the fix https://github.com/ocaml-community/yojson/pull/150 works:
1. Uninstall the yojson package from opam
2. Install the version of yojson with the fix (https://github.com/ocaml-community/yojson/pull/150) using `make && make install`
3. Build and test atd with `make && make test`

**Comment by mbacarella** [comment]
Any blockers left? Any help needed to get this merged and released?

**Comment by mjambon** [comment]
> Any blockers left? Any help needed to get this merged and released?

We're waiting for yojson 2.0.2 to be released, which fixes a bug in a function that's used by atdgen-generated code only and wasn't tested in yojson (https://github.com/ocaml-community/yojson/pull/150).

**Comment by mjambon** [comment]
I just fixed the dependencies on yojson >= 2.0.2 in the opam files. This should be the last remaining error, based on manual testing I did [earlier](https://github.com/ahrefs/atd/pull/311#issuecomment-1191861021). Once yojson 2.0.2 or 2.1.0 is released, we will re-run the CI jobs and everything should be green at that point.

**Comment by Leonidas-from-XIV** [comment]
I had hoped to get https://github.com/ocaml-community/yojson/pull/147 merged before releasing 2.0.2 but oh well, might as well do the release today.

**Comment by Leonidas-from-XIV** [comment]
2.0.2 released and waiting to get merged to OPAM-Repository: https://github.com/ocaml/opam-repository/pull/21960

**Comment by Leonidas-from-XIV** [comment]
Nice, thanks for the work. Let's hope that it'll stick this time :-)

**Pull request merged**
