### PR TITLE
Create pylint.yml

### PR DESCRIPTION
**Pull request by Caprice2201**
### PR checklist

- [ ] New code has tests to catch future regressions
- [ ] Documentation is up-to-date
- [ ] `CHANGES.md` is up-to-date

### CODE REVIEW

**Comment by mjambon** [comment]
Thank you... Can you please describe what this is for? (preferably as comments in the code)

**Comment by mjambon** [comment]
Also, we use CircleCI, not GitHub Actions (because it offers ssh drop-in and good documentation).

**Comment by mjambon** [comment]
This user @Caprice2201 is new to GitHub and has been posting junk here and there. Closing.

**Review by Caprice2201 — COMMENTED** [review]
𝑎𝑐𝑐𝑒𝑝𝑡𝑒𝑑

**Pull request closed without merging**
