### PR TITLE
Build the tutorials with dune

### PR DESCRIPTION
**Pull request by mbarbin**
This is a follow-up to #396 to build more tutorials with dune.

I added context as a resonse to @mjambon in the other PR:

`During my exploration of atd, I've been going through the documentation, tutorials, and experimenting with building things using dune. I've found that having the demos built with dune enhances my learning experience, as I can see the types within my editor using Merlin. This will also ensure that the demos are checked during your build process and kept up to date. That's what led me to create this PR.`

Thank you for considering my changes and for your work on `atd`.

### PR checklist

- [x] New code has tests to catch future regressions
This PR adds a new test that is run as part of `dune runtest`.
- [x] Documentation is up-to-date 
This PR does not involve changes that require updates to the documentation.
- [x] CHANGES.md is up-to-date
This PR does not involve changes that require updates to CHANGES.md.

### CODE REVIEW

**Comment by mjambon** [comment]
Excellent! Thank you!

**Comment by mjambon** [comment]
@mbarbin I got an email from CircleCI telling me that the CI checks were not passing. I believe it's because it didn't run on your branch (because it was from a forked repo). The errors are about an unused value, see https://app.circleci.com/pipelines/github/ahrefs/atd/425/workflows/7f5c941e-cc98-4b65-869f-d70c48ac1ee4/jobs/814 (ocaml 4.14) and https://app.circleci.com/pipelines/github/ahrefs/atd/425/workflows/7f5c941e-cc98-4b65-869f-d70c48ac1ee4/jobs/815 (ocaml 4.08).

**Comment by mjambon** [comment]
This should fix it: https://github.com/ahrefs/atd/pull/409

**Comment by mbarbin** [comment]
@mjambon it seems the failure was due to a change from another PR that got merged before this one. Thank you for fixing the build and merging!

**Pull request merged**
