### PR TITLE
Deny inline record type

### LINKED ISSUE #209: inline records create code with syntax errors
I was writing a ATD doc with something like the following:

`type foo = [ Foo of {x: int}]`

but this generates the incorrect OCaml code:

```ocaml
type foo = [`Foo of {x: int}]
```

I was expecting that ATD would give a syntax error on this.

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #209 
It is one way to address this problem by denying anonymous record types at record field type or variant field type.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks for your contribution. Could you add a test case for this?

**Comment by rr0gi** [comment]
superseded by #224

**Review by Caprice2201 — COMMENTED** [review]
46bd

**Comment by Caprice2201** [comment]
disallow-inline-record-type

**Pull request closed without merging**
